# mkdocs.yml
site_name: "Discord API's structures"
repo_url: https://github.com/FasterSpeeding/discord-api-spec-repr
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences
  # - markdown_include.include
  - toc:
      permalink: "#"

plugins:
  - autorefs
  - search
  - minify:
      minify_html: true
  - swagger-ui-tag

watch:
  - docs
