name: Freeze PR dependency changes

on:
  pull_request:
    branches:
      - master
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  freeze-pr-dep-changes:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    uses: FasterSpeeding/Piped/.github/workflows/freeze-for-pr.yml@2b70f426ace02313b21362ab8837ab9ced3dc40a
    secrets: inherit
