name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    uses: FasterSpeeding/Piped/.github/workflows/lint.yml@13c12d52c5d5e27d8a87398f14e469745117443b
