name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@9c2b284f6fb48a4b294728b63fa4032b15104e00
    secrets: inherit
