name: Reformat PR code

on:
  pull_request:
    branches:
      - master

jobs:
  reformat:
    uses: FasterSpeeding/Piped/.github/workflows/reformat.yml@45039ff4ec17015d4963e6cc9e1c6d7a21add80a
    secrets: inherit
